# Generated by Django 5.0.6 on 2024-06-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('proveedor', models.CharField(max_length=255)),
                ('id_producto', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
